# Generated by Django 3.1.1 on 2021-06-05 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('PH', 'PHD')], default='FR', max_length=2)),
                ('department', models.CharField(choices=[('1', 'COMP'), ('2', 'MATH'), ('3', 'ELCT'), ('4', 'PHYS')], default='1', max_length=4)),
                ('type', models.CharField(choices=[('1', 'TCH'), ('2', 'STD')], default='2', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
