# Generated by Django 3.1.1 on 2021-06-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('masters', models.BooleanField()),
                ('bachelor', models.BooleanField()),
                ('prof_fname', models.CharField(max_length=30)),
                ('prof_lname', models.CharField(max_length=30)),
                ('prof_id', models.CharField(max_length=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach_main.request')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.CharField(max_length=500)),
                ('replier_fname', models.CharField(max_length=30)),
                ('replier_lname', models.CharField(max_length=30)),
                ('replier_id', models.CharField(max_length=7)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach_main.request')),
            ],
        ),
    ]
