# Generated by Django 3.1.1 on 2021-02-02 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teach_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='prof_fname',
            field=models.CharField(default='aa', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='prof_id',
            field=models.CharField(default=23, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='prof_lname',
            field=models.CharField(default='hh', max_length=30),
            preserve_default=False,
        ),
    ]
