# Generated by Django 3.1.1 on 2021-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_main', '0002_auto_20210202_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
