# Generated by Django 3.1.1 on 2021-06-08 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teach_main', '0002_auto_20210608_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replier_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='prof_id',
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
