# Generated by Django 3.1.1 on 2021-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_main', '0004_storedreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
