# Generated by Django 3.1.1 on 2021-06-17 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teach_main', '0007_auto_20210608_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreplies',
            name='datetime_of_bookmark',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
